CREATE TABLE country(
 country_id SERIAL,
 country VARCHAR(100) NOT NULL,
 PRIMARY KEY(country_id)
);

-- ----------------------------
-- Records of country
-- ----------------------------
INSERT INTO country(country) VALUES ('Afghanistan');
INSERT INTO country(country) VALUES ('Algeria');
INSERT INTO country(country) VALUES ( 'American Samoa');
INSERT INTO country(country) VALUES ( 'Angola');
INSERT INTO country(country) VALUES ('Anguilla');
INSERT INTO country(country) VALUES ('Argentina');
INSERT INTO country(country) VALUES ('Armenia');
INSERT INTO country(country) VALUES ('Australia');
INSERT INTO country(country) VALUES ('Austria');
INSERT INTO country(country) VALUES ('Azerbaijan');
INSERT INTO country(country) VALUES ('Bahrain');
INSERT INTO country(country) VALUES ('Bangladesh');
INSERT INTO country(country) VALUES ('Belarus');
INSERT INTO country(country) VALUES ('Bolivia');
INSERT INTO country(country) VALUES ('Brazil');
INSERT INTO country(country) VALUES ('Brunei');
INSERT INTO country(country) VALUES ('Bulgaria');
INSERT INTO country(country) VALUES ('Cambodia');
INSERT INTO country(country) VALUES ('Cameroon');
INSERT INTO country(country) VALUES ('Canada');
INSERT INTO country(country) VALUES ('Chad');
INSERT INTO country(country) VALUES ('Chile');
INSERT INTO country(country) VALUES ('China');
INSERT INTO country(country) VALUES ('Colombia');
INSERT INTO country(country) VALUES ('Congo, The Democratic Republic of the');
INSERT INTO country(country) VALUES ('Czech Republic');
INSERT INTO country(country) VALUES ('Dominican Republic');
INSERT INTO country(country) VALUES ('Ecuador');
INSERT INTO country(country) VALUES ('Egypt');
INSERT INTO country(country) VALUES ('Estonia');
INSERT INTO country(country) VALUES ('Ethiopia');
INSERT INTO country(country) VALUES ('Faroe Islands');
INSERT INTO country(country) VALUES ('Finland');
INSERT INTO country(country) VALUES ('France');
INSERT INTO country(country) VALUES ('French Guiana');
INSERT INTO country(country) VALUES ('French Polynesia');
INSERT INTO country(country) VALUES ('Gambia');
INSERT INTO country(country) VALUES ('Germany');
INSERT INTO country(country) VALUES ('Greece');
INSERT INTO country(country) VALUES ('Greenland');
INSERT INTO country(country) VALUES ('Holy See (Vatican City State)');
INSERT INTO country(country) VALUES ('Hong Kong');
INSERT INTO country(country) VALUES ('Hungary');
INSERT INTO country(country) VALUES ('India');
INSERT INTO country(country) VALUES ('Indonesia');
INSERT INTO country(country) VALUES ('Iran');
INSERT INTO country(country) VALUES ('Iraq');
INSERT INTO country(country) VALUES ('Israel');
INSERT INTO country(country) VALUES ('Italy');
INSERT INTO country(country) VALUES ('Japan');
INSERT INTO country(country) VALUES ('Kazakstan');
INSERT INTO country(country) VALUES ('Kenya');
INSERT INTO country(country) VALUES ('Kuwait');
INSERT INTO country(country) VALUES ('Latvia');
INSERT INTO country(country) VALUES ('Liechtenstein');
INSERT INTO country(country) VALUES ('Lithuania');
INSERT INTO country(country) VALUES ('Madagascar');
INSERT INTO country(country) VALUES ('Malawi');
INSERT INTO country(country) VALUES ('Malaysia');
INSERT INTO country(country) VALUES ('Mexico');
INSERT INTO country(country) VALUES ('Moldova');
INSERT INTO country(country) VALUES ('Morocco');
INSERT INTO country(country) VALUES ('Mozambique');
INSERT INTO country(country) VALUES ('Myanmar');
INSERT INTO country(country) VALUES ('Nauru');
INSERT INTO country(country) VALUES ('Nepal');
INSERT INTO country(country) VALUES ('Netherlands');
INSERT INTO country(country) VALUES ('New Zealand');
INSERT INTO country(country) VALUES ('Nigeria');
INSERT INTO country(country) VALUES ('North Korea');
INSERT INTO country(country) VALUES ('Oman');
INSERT INTO country(country) VALUES ('Pakistan');
INSERT INTO country(country) VALUES ('Paraguay');
INSERT INTO country(country) VALUES ('Peru');
INSERT INTO country(country) VALUES ('Philippines');
INSERT INTO country(country) VALUES ('Poland');
INSERT INTO country(country) VALUES ('Puerto Rico');
INSERT INTO country(country) VALUES ('Romania');
INSERT INTO country(country) VALUES ('Runion');
INSERT INTO country(country) VALUES ('Russian Federation');
INSERT INTO country(country) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO country(country) VALUES ('Saudi Arabia');
INSERT INTO country(country) VALUES ('Senegal');
INSERT INTO country(country) VALUES ('Slovakia');
INSERT INTO country(country) VALUES ('South Africa');
INSERT INTO country(country) VALUES ('South Korea');
INSERT INTO country(country) VALUES ('Spain');
INSERT INTO country(country) VALUES ('Sri Lanka');
INSERT INTO country(country) VALUES ('Sudan');
INSERT INTO country(country) VALUES ('Sweden');
INSERT INTO country(country) VALUES ('Switzerland');
INSERT INTO country(country) VALUES ('Taiwan');
INSERT INTO country(country) VALUES ('Tanzania');
INSERT INTO country(country) VALUES ('Thailand');
INSERT INTO country(country) VALUES ('Tonga');
INSERT INTO country(country) VALUES ('Tunisia');
INSERT INTO country(country) VALUES ('Turkey');
INSERT INTO country(country) VALUES ('Turkmenistan');
INSERT INTO country(country) VALUES ('Tuvalu');
INSERT INTO country(country) VALUES ('Ukraine');
INSERT INTO country(country) VALUES ('United Arab Emirates');
INSERT INTO country(country) VALUES ('United Kingdom');
INSERT INTO country(country) VALUES ('United States');
INSERT INTO country(country) VALUES ('Venezuela');
INSERT INTO country(country) VALUES ('Vietnam');
INSERT INTO country(country) VALUES ('Virgin Islands, U.S.');
INSERT INTO country(country) VALUES ('Yemen');
INSERT INTO country(country) VALUES ('Yugoslavia');
INSERT INTO country(country) VALUES ('Zambia');
